/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatCompletionResponseChoicesInner } from '../models/ChatCompletionResponseChoicesInner';
import { HttpFile } from '../http/http';

export class Chat completion response {
    'choices'?: Array<ChatCompletionResponseChoicesInner>;
    'id'?: string;
    'model'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "choices",
            "baseName": "choices",
            "type": "Array<ChatCompletionResponseChoicesInner>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Chat completion response.attributeTypeMap;
    }

    public constructor() {
    }
}

