/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Chatcompletionmessage } from '../models/Chatcompletionmessage';
import { HttpFile } from '../http/http';

export class ChatCompletionResponseChoicesInner {
    'message'?: Chat completion message;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "Chat completion message",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatCompletionResponseChoicesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

