/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompletionResponseChoicesInner } from '../models/CompletionResponseChoicesInner';
import { HttpFile } from '../http/http';

/**
* A completion response from the model.
*/
export class Completion response {
    'choices'?: Array<CompletionResponseChoicesInner>;
    'id'?: string;
    'model'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "choices",
            "baseName": "choices",
            "type": "Array<CompletionResponseChoicesInner>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Completion response.attributeTypeMap;
    }

    public constructor() {
    }
}

