/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ContentModerationPolicy {
    'active'?: boolean;
    'blockedContentTypes'?: Array<ContentModerationPolicyBlockedContentTypesEnum>;
    'name'?: string;
    'scoreThreshold'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "blockedContentTypes",
            "baseName": "blocked_content_types",
            "type": "Array<ContentModerationPolicyBlockedContentTypesEnum>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "scoreThreshold",
            "baseName": "score_threshold",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContentModerationPolicy.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ContentModerationPolicyBlockedContentTypesEnum {
    Toxic = 'toxic',
    Obscene = 'obscene',
    Insult = 'insult',
    IdentityHate = 'identity_hate',
    Threat = 'threat',
    SevereToxic = 'severe_toxic'
}

