/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Chatcompletionmessage } from '../models/Chatcompletionmessage';
import { HttpFile } from '../http/http';

/**
* Creates a model response for the given chat conversation.
*/
export class Create chat completion {
    'messages': Array<Chat completion message>;
    'model': string;
    'stream'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<Chat completion message>",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "stream",
            "baseName": "stream",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Create chat completion.attributeTypeMap;
    }

    public constructor() {
    }
}

