/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DlpPolicy } from '../models/DlpPolicy';
import { HttpFile } from '../http/http';

export class DlpPolicyParams {
    'dlpPolicy'?: DlpPolicy;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dlpPolicy",
            "baseName": "dlp_policy",
            "type": "DlpPolicy",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DlpPolicyParams.attributeTypeMap;
    }

    public constructor() {
    }
}

