/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DlpPolicyAnonymizer } from '../models/DlpPolicyAnonymizer';
import { DlpZsnerPolicyEntitiesInner } from '../models/DlpZsnerPolicyEntitiesInner';
import { HttpFile } from '../http/http';

export class DlpZsnerPolicy {
    'active'?: boolean;
    'anonymizer'?: DlpPolicyAnonymizer;
    'entities'?: Array<DlpZsnerPolicyEntitiesInner>;
    'name'?: string;
    'response'?: DlpZsnerPolicyResponseEnum;
    'scoreThreshold'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "anonymizer",
            "baseName": "anonymizer",
            "type": "DlpPolicyAnonymizer",
            "format": ""
        },
        {
            "name": "entities",
            "baseName": "entities",
            "type": "Array<DlpZsnerPolicyEntitiesInner>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "DlpZsnerPolicyResponseEnum",
            "format": ""
        },
        {
            "name": "scoreThreshold",
            "baseName": "score_threshold",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DlpZsnerPolicy.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum DlpZsnerPolicyResponseEnum {
    Block = 'block',
    Alert = 'alert',
    Anonymize = 'anonymize'
}

