/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DlpZsnerPolicy } from '../models/DlpZsnerPolicy';
import { HttpFile } from '../http/http';

export class DlpZsnerPolicyParams {
    'dlpZsnerPolicy'?: DlpZsnerPolicy;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dlpZsnerPolicy",
            "baseName": "dlp_zsner_policy",
            "type": "DlpZsnerPolicy",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DlpZsnerPolicyParams.attributeTypeMap;
    }

    public constructor() {
    }
}

