/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DreamcatcherWebPresidioPolicyControllerScan200Response {
    'violatesPolicy'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "violatesPolicy",
            "baseName": "violates_policy",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DreamcatcherWebPresidioPolicyControllerScan200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

