/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListModelsResponseDataInner } from '../models/ListModelsResponseDataInner';
import { HttpFile } from '../http/http';

export class ListModelsResponse {
    'data'?: Array<ListModelsResponseDataInner>;
    'object'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ListModelsResponseDataInner>",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListModelsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

