/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentModerationPolicy } from '../models/ContentModerationPolicy';
import { DlpPolicy } from '../models/DlpPolicy';
import { DlpZsnerPolicy } from '../models/DlpZsnerPolicy';
import { HttpFile } from '../http/http';

export class ShowEndpointResponse {
    'contentModerationPolicies'?: ContentModerationPolicy;
    'dlpPolicies'?: DlpPolicy;
    'dlpZsnerPolicies'?: DlpZsnerPolicy;
    'name'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contentModerationPolicies",
            "baseName": "content_moderation_policies",
            "type": "ContentModerationPolicy",
            "format": ""
        },
        {
            "name": "dlpPolicies",
            "baseName": "dlp_policies",
            "type": "DlpPolicy",
            "format": ""
        },
        {
            "name": "dlpZsnerPolicies",
            "baseName": "dlp_zsner_policies",
            "type": "DlpZsnerPolicy",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShowEndpointResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

